spring.application.name=web-ms
server.port=${SERVER_PORT:8080}

clientes.service.url=${CLIENTES_SERVICE_URL:http://localhost:8081}
estoque.service.url=${ESTOQUE_SERVICE_URL:http://localhost:8082}
pedidos.service.url=${PEDIDOS_SERVICE_URL:http://localhost:8083}
