server {
    listen 9000;
    server_name _;

    proxy_http_version 1.1;
    proxy_set_header Host $host;
    proxy_set_header X-Real-IP $remote_addr;
    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    proxy_set_header X-Forwarded-Proto $scheme;

    location /api/clientes {
        proxy_pass http://clientes-service:8081;
    }

    location /api/estoques {
        proxy_pass http://estoque-service:8082;
    }

    location /api/pedidos {
        proxy_pass http://pedidos-service:8083;
    }

    location / {
        return 404;
    }
}
